apiVersion: v1
kind: Pod
metadata:
  name: testresultserver
  labels:
    app: testresultserver
spec:
  hostname: testresultserver
  volumes:
  - name: www
    hostPath:
      path: /run/desktop/mnt/host/c/www
      type: DirectoryOrCreate
  containers:
  - name: testresultserver
    image: testresultserver:latest
    #IfNotPresent - Nesscary for Windows Docker Desktop Environment. Image is already there ;-)
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: www
      mountPath: /www
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: svc-testresultserver
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30010
  selector:
    app: testresultserver
